[package]
name = "example"
version = "0.2.0"
edition = "2024"

[[bin]]
name="encoder"
path="src/encoder.rs"

[[bin]]
name="encoder2"
path="src/encoder2.rs"

[[bin]]
name="decoder"
path="src/decoder.rs"

[[bin]]
name="decoder2"
path="src/decoder2.rs"

[dependencies]
utf8sten={git="https://github.com/11mushroom/UTF8sten_lib_oxidised", rev = "a6370d0b8b11006c7fa9bbf4fdc5279e00211224"}
